# Generated by Django 4.1.7 on 2023-03-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description_short', models.CharField(max_length=50, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное описание')),
            ],
        ),
    ]
