# Generated by Django 4.1.7 on 2023-03-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0002_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(default=0, max_length=10, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinates',
            name='lon',
            field=models.FloatField(default=0, max_length=10, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
