# Generated by Django 4.1.7 on 2023-03-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0003_coordinates_lat_coordinates_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
