# Generated by Django 4.1.7 on 2023-03-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Номер картинки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
