# Generated by Django 4.1.7 on 2023-04-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0006_image_index_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='map_poster.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map_poster.place', verbose_name='Место'),
        ),
    ]
