# Generated by Django 4.1.7 on 2023-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0007_alter_coordinates_place_alter_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=1, max_length=10, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(default=1, max_length=10, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
