# Generated by Django 4.1.7 on 2023-04-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0008_place_lat_place_lon_delete_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='image',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
