# Generated by Django 4.1.7 on 2023-04-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0009_alter_image_options_image_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['object_id']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='my_order',
        ),
        migrations.AddField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Позиция'),
        ),
    ]
