# Generated by Django 3.2.18 on 2023-04-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0012_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
    ]
