# Generated by Django 3.2.18 on 2023-04-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0013_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
