# Generated by Django 3.2.18 on 2023-04-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_poster', '0014_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
